### ISSUE TITLE
Permission to non-op players

### ISSUE THREAD

**Issue by erversonkirit** [Muqsit/Sell#2]
Hello sir can u put permissions to the non-op players so they can use the command

**Comment by Muqsit** [comment]
Permissions are already set. You can permit non op players to use the command through permission-based plugins like PurePerms.

``` yaml
permission:
  sell:
    default: op
    children:
      sell.hand:
        default: op
```
